'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FAlarmHistoryFilter

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FAlarmHistoryFilter.sfc"), False)
        DateTimeIn1 = loader.Find("DateTimeIn1")
        Label001 = loader.Find("Label001")
        DateTimeIn2 = loader.Find("DateTimeIn2")
        cmdOk = loader.Find("cmdOk")
        Label000 = loader.Find("Label000")
        Shape1 = loader.Find("Shape1")
        Label2 = loader.Find("Label2")
        Shape2 = loader.Find("Shape2")
        RadioButton5 = loader.Find("RadioButton5")
        RadioButton1 = loader.Find("RadioButton1")
        RadioButton4 = loader.Find("RadioButton4")
        RadioButton2 = loader.Find("RadioButton2")
        RadioButton3 = loader.Find("RadioButton3")
        CType(DateTimeIn1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label001, System.ComponentModel.ISupportInitialize).EndInit()
        CType(DateTimeIn2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdOk, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label000, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(RadioButton5, System.ComponentModel.ISupportInitialize).EndInit()
        CType(RadioButton1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(RadioButton4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(RadioButton2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(RadioButton3, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents DateTimeIn1 As VisiWinNET.Forms.DateTimeIn
    Friend WithEvents Label001 As VisiWinNET.Forms.Label
    Friend WithEvents DateTimeIn2 As VisiWinNET.Forms.DateTimeIn
    Friend WithEvents cmdOk As VisiWinNET.Forms.CommandButton
    Friend WithEvents Label000 As VisiWinNET.Forms.Label
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Label2 As VisiWinNET.Forms.Label
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents RadioButton5 As VisiWinNET.Forms.RadioButton
    Friend WithEvents RadioButton1 As VisiWinNET.Forms.RadioButton
    Friend WithEvents RadioButton4 As VisiWinNET.Forms.RadioButton
    Friend WithEvents RadioButton2 As VisiWinNET.Forms.RadioButton
    Friend WithEvents RadioButton3 As VisiWinNET.Forms.RadioButton

End Class