'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FAlarms

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FAlarms.sfc"), False)
        cmdAlarmHistory = loader.Find("cmdAlarmHistory")
        cmdAcknowledgeSelect = loader.Find("cmdAcknowledgeSelect")
        cmdAcknowledgeAll = loader.Find("cmdAcknowledgeAll")
        AlarmList = loader.Find("AlarmList")
        cmdReturn = loader.Find("cmdReturn")
        GroupBox = loader.Find("GroupBox")
        Shape1 = loader.Find("Shape1")
        Shape2 = loader.Find("Shape2")
        Shape3 = loader.Find("Shape3")
        Shape4 = loader.Find("Shape4")
        CType(cmdAlarmHistory, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdAcknowledgeSelect, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdAcknowledgeAll, System.ComponentModel.ISupportInitialize).EndInit()
        CType(AlarmList, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdReturn, System.ComponentModel.ISupportInitialize).EndInit()
        CType(GroupBox, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox.ResumeLayout(False)
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape4, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents cmdAlarmHistory As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdAcknowledgeSelect As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdAcknowledgeAll As VisiWinNET.Forms.CommandButton
    Friend WithEvents AlarmList As VisiWinNET.Forms.Alarm.AlarmList
    Friend WithEvents cmdReturn As VisiWinNET.Forms.CommandButton
    Friend WithEvents GroupBox As VisiWinNET.Forms.GroupBox
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape3 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape4 As VisiWinNET.Forms.Shape

End Class