'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FAlphaPad

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FAlphaPad.sfc"), False)
        grpBorder = loader.Find("grpBorder")
        cmd111 = loader.Find("cmd111")
        cmdShiftRight = loader.Find("cmdShiftRight")
        cmd211 = loader.Find("cmd211")
        cmdAltGr = loader.Find("cmdAltGr")
        cmdClear = loader.Find("cmdClear")
        cmdEnd = loader.Find("cmdEnd")
        cmdHome = loader.Find("cmdHome")
        numEdit = loader.Find("numEdit")
        cmdEsc = loader.Find("cmdEsc")
        cmdDel = loader.Find("cmdDel")
        cmdUp = loader.Find("cmdUp")
        cmdRight = loader.Find("cmdRight")
        cmdLeft = loader.Find("cmdLeft")
        cmdSpace = loader.Find("cmdSpace")
        cmdCtrlLeft = loader.Find("cmdCtrlLeft")
        cmdCtrlRight = loader.Find("cmdCtrlRight")
        cmdShiftLeft = loader.Find("cmdShiftLeft")
        cmd310 = loader.Find("cmd310")
        cmd39 = loader.Find("cmd39")
        cmd38 = loader.Find("cmd38")
        cmd37 = loader.Find("cmd37")
        cmd36 = loader.Find("cmd36")
        cmd35 = loader.Find("cmd35")
        cmd34 = loader.Find("cmd34")
        cmd33 = loader.Find("cmd33")
        cmd32 = loader.Find("cmd32")
        cmd31 = loader.Find("cmd31")
        cmd30 = loader.Find("cmd30")
        cmd210 = loader.Find("cmd210")
        cmd29 = loader.Find("cmd29")
        cmd28 = loader.Find("cmd28")
        cmd27 = loader.Find("cmd27")
        cmd26 = loader.Find("cmd26")
        cmd25 = loader.Find("cmd25")
        cmd24 = loader.Find("cmd24")
        cmd23 = loader.Find("cmd23")
        cmd22 = loader.Find("cmd22")
        cmd21 = loader.Find("cmd21")
        cmd20 = loader.Find("cmd20")
        cmdCapsLock = loader.Find("cmdCapsLock")
        cmdTab = loader.Find("cmdTab")
        cmdBack = loader.Find("cmdBack")
        cmd110 = loader.Find("cmd110")
        cmd19 = loader.Find("cmd19")
        cmd18 = loader.Find("cmd18")
        cmd17 = loader.Find("cmd17")
        cmd16 = loader.Find("cmd16")
        cmd15 = loader.Find("cmd15")
        cmd14 = loader.Find("cmd14")
        cmd13 = loader.Find("cmd13")
        cmd12 = loader.Find("cmd12")
        cmd11 = loader.Find("cmd11")
        cmd10 = loader.Find("cmd10")
        cmd012 = loader.Find("cmd012")
        cmd011 = loader.Find("cmd011")
        cmd010 = loader.Find("cmd010")
        cmd09 = loader.Find("cmd09")
        cmd08 = loader.Find("cmd08")
        cmd07 = loader.Find("cmd07")
        cmd06 = loader.Find("cmd06")
        cmd05 = loader.Find("cmd05")
        cmd04 = loader.Find("cmd04")
        cmd03 = loader.Find("cmd03")
        cmd02 = loader.Find("cmd02")
        cmd01 = loader.Find("cmd01")
        cmd00 = loader.Find("cmd00")
        lblCaption = loader.Find("lblCaption")
        cmdDown = loader.Find("cmdDown")
        cmdEnter = loader.Find("cmdEnter")
        lblInputBack = loader.Find("lblInputBack")
        CType(grpBorder, System.ComponentModel.ISupportInitialize).EndInit()
        grpBorder.ResumeLayout(False)
        CType(cmd111, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdShiftRight, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd211, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdAltGr, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdClear, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdEnd, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdHome, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdEsc, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdDel, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdUp, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdRight, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdLeft, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdSpace, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdCtrlLeft, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdCtrlRight, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdShiftLeft, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd310, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd39, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd38, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd37, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd36, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd35, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd34, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd33, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd32, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd31, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd30, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd210, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd29, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd28, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd27, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd26, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd25, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd24, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd23, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd22, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd21, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd20, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdCapsLock, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdTab, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdBack, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd110, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd19, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd18, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd17, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd16, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd15, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd14, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd13, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd12, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd11, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd10, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd012, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd011, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd010, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd09, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd08, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd07, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd06, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd05, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd04, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd03, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd02, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd01, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd00, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblCaption, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdDown, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdEnter, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblInputBack, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents grpBorder As VisiWinNET.Forms.GroupBox
    Friend WithEvents cmd111 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdShiftRight As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd211 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdAltGr As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdClear As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdEnd As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdHome As VisiWinNET.Forms.CommandButton
    Friend WithEvents numEdit As VisiWinNET.Forms.Internals.NumEdit
    Friend WithEvents cmdEsc As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdDel As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdUp As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdRight As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdLeft As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdSpace As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdCtrlLeft As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdCtrlRight As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdShiftLeft As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd310 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd39 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd38 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd37 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd36 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd35 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd34 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd33 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd32 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd31 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd30 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd210 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd29 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd28 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd27 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd26 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd25 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd24 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd23 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd22 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd21 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd20 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdCapsLock As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdTab As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdBack As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd110 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd19 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd18 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd17 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd16 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd15 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd14 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd13 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd12 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd11 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd10 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd012 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd011 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd010 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd09 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd08 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd07 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd06 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd05 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd04 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd03 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd02 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd01 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd00 As VisiWinNET.Forms.CommandButton
    Friend WithEvents lblCaption As VisiWinNET.Forms.Label
    Friend WithEvents cmdDown As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdEnter As VisiWinNET.Forms.CommandButton
    Friend WithEvents lblInputBack As VisiWinNET.Forms.Label

End Class