'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FCentral

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FCentral.sfc"), False)
        TouchKeyboard = loader.Find("TouchKeyboard")
        Shape5 = loader.Find("Shape5")
        Shape1 = loader.Find("Shape1")
        Shape2 = loader.Find("Shape2")
        Shape3 = loader.Find("Shape3")
        Shape4 = loader.Find("Shape4")
        GroupBox1 = loader.Find("GroupBox1")
        GroupBox2 = loader.Find("GroupBox2")
        PictureBox1 = loader.Find("PictureBox1")
        Label2 = loader.Find("Label2")
        cmdContinue = loader.Find("cmdContinue")
        GroupBox3 = loader.Find("GroupBox3")
        DateTimeOut1 = loader.Find("DateTimeOut1")
        Label4 = loader.Find("Label4")
        PictureBox2 = loader.Find("PictureBox2")
        Label1 = loader.Find("Label1")
        CType(TouchKeyboard, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape5, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(GroupBox1, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox1.ResumeLayout(False)
        CType(GroupBox2, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox2.ResumeLayout(False)
        CType(PictureBox1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdContinue, System.ComponentModel.ISupportInitialize).EndInit()
        CType(GroupBox3, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox3.ResumeLayout(False)
        CType(DateTimeOut1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(PictureBox2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label1, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents TouchKeyboard As VisiWinNET.Forms.TouchKeyboard
    Friend WithEvents Shape5 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape3 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape4 As VisiWinNET.Forms.Shape
    Friend WithEvents GroupBox1 As VisiWinNET.Forms.GroupBox
    Friend WithEvents GroupBox2 As VisiWinNET.Forms.GroupBox
    Friend WithEvents PictureBox1 As VisiWinNET.Forms.PictureBox
    Friend WithEvents Label2 As VisiWinNET.Forms.Label
    Friend WithEvents cmdContinue As VisiWinNET.Forms.CommandButton
    Friend WithEvents GroupBox3 As VisiWinNET.Forms.GroupBox
    Friend WithEvents DateTimeOut1 As VisiWinNET.Forms.DateTimeOut
    Friend WithEvents Label4 As VisiWinNET.Forms.Label
    Friend WithEvents PictureBox2 As VisiWinNET.Forms.PictureBox
    Friend WithEvents Label1 As VisiWinNET.Forms.Label

End Class