'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FColorSelect

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FColorSelect.sfc"), False)
        Shape1 = loader.Find("Shape1")
        grp = loader.Find("grp")
        vinBlue = loader.Find("vinBlue")
        vinGreen = loader.Find("vinGreen")
        vinRed = loader.Find("vinRed")
        cmdColor1 = loader.Find("cmdColor1")
        cmdColor2 = loader.Find("cmdColor2")
        cmdColor3 = loader.Find("cmdColor3")
        cmdColor4 = loader.Find("cmdColor4")
        cmdColor5 = loader.Find("cmdColor5")
        cmdColor6 = loader.Find("cmdColor6")
        cmdColor7 = loader.Find("cmdColor7")
        cmdColor8 = loader.Find("cmdColor8")
        cmdColor9 = loader.Find("cmdColor9")
        cmdColor10 = loader.Find("cmdColor10")
        cmdColor11 = loader.Find("cmdColor11")
        cmdColor12 = loader.Find("cmdColor12")
        cmdColor13 = loader.Find("cmdColor13")
        cmdColor14 = loader.Find("cmdColor14")
        cmdColor15 = loader.Find("cmdColor15")
        cmdColor16 = loader.Find("cmdColor16")
        cmdColor17 = loader.Find("cmdColor17")
        cmdColor18 = loader.Find("cmdColor18")
        cmdColor19 = loader.Find("cmdColor19")
        cmdColor20 = loader.Find("cmdColor20")
        cmdColor21 = loader.Find("cmdColor21")
        cmdColor22 = loader.Find("cmdColor22")
        cmdColor23 = loader.Find("cmdColor23")
        cmdColor24 = loader.Find("cmdColor24")
        cmdColor25 = loader.Find("cmdColor25")
        cmdColor26 = loader.Find("cmdColor26")
        cmdColor27 = loader.Find("cmdColor27")
        cmdColor28 = loader.Find("cmdColor28")
        cmdColor29 = loader.Find("cmdColor29")
        cmdColor30 = loader.Find("cmdColor30")
        cmdColor31 = loader.Find("cmdColor31")
        cmdColor32 = loader.Find("cmdColor32")
        cmdColor33 = loader.Find("cmdColor33")
        cmdColor34 = loader.Find("cmdColor34")
        cmdColor35 = loader.Find("cmdColor35")
        cmdColor36 = loader.Find("cmdColor36")
        cmdColor37 = loader.Find("cmdColor37")
        cmdColor38 = loader.Find("cmdColor38")
        cmdColor39 = loader.Find("cmdColor39")
        cmdColor40 = loader.Find("cmdColor40")
        cmdColor41 = loader.Find("cmdColor41")
        cmdColor42 = loader.Find("cmdColor42")
        cmdColor43 = loader.Find("cmdColor43")
        cmdColor44 = loader.Find("cmdColor44")
        cmdColor45 = loader.Find("cmdColor45")
        cmdColor46 = loader.Find("cmdColor46")
        cmdColor47 = loader.Find("cmdColor47")
        cmdColor48 = loader.Find("cmdColor48")
        cmdColor49 = loader.Find("cmdColor49")
        cmdColor50 = loader.Find("cmdColor50")
        cmdColor51 = loader.Find("cmdColor51")
        cmdColor52 = loader.Find("cmdColor52")
        cmdColor53 = loader.Find("cmdColor53")
        cmdColor54 = loader.Find("cmdColor54")
        cmdColor55 = loader.Find("cmdColor55")
        cmdColor56 = loader.Find("cmdColor56")
        cmdColor57 = loader.Find("cmdColor57")
        cmdColor58 = loader.Find("cmdColor58")
        cmdColor59 = loader.Find("cmdColor59")
        cmdColor60 = loader.Find("cmdColor60")
        cmdColor61 = loader.Find("cmdColor61")
        cmdColor62 = loader.Find("cmdColor62")
        cmdColor63 = loader.Find("cmdColor63")
        cmdColor64 = loader.Find("cmdColor64")
        cmdColor65 = loader.Find("cmdColor65")
        cmdColor66 = loader.Find("cmdColor66")
        cmdColor67 = loader.Find("cmdColor67")
        cmdColor68 = loader.Find("cmdColor68")
        cmdColor69 = loader.Find("cmdColor69")
        cmdColor70 = loader.Find("cmdColor70")
        cmdColor71 = loader.Find("cmdColor71")
        cmdColor72 = loader.Find("cmdColor72")
        cmdColor73 = loader.Find("cmdColor73")
        cmdColor74 = loader.Find("cmdColor74")
        cmdColor75 = loader.Find("cmdColor75")
        cmdIndividualColor = loader.Find("cmdIndividualColor")
        pbxSelection = loader.Find("pbxSelection")
        Label1 = loader.Find("Label1")
        Shape2 = loader.Find("Shape2")
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(grp, System.ComponentModel.ISupportInitialize).EndInit()
        grp.ResumeLayout(False)
        CType(vinBlue, System.ComponentModel.ISupportInitialize).EndInit()
        CType(vinGreen, System.ComponentModel.ISupportInitialize).EndInit()
        CType(vinRed, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor5, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor6, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor7, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor8, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor9, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor10, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor11, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor12, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor13, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor14, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor15, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor16, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor17, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor18, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor19, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor20, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor21, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor22, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor23, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor24, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor25, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor26, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor27, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor28, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor29, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor30, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor31, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor32, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor33, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor34, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor35, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor36, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor37, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor38, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor39, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor40, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor41, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor42, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor43, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor44, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor45, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor46, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor47, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor48, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor49, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor50, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor51, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor52, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor53, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor54, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor55, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor56, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor57, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor58, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor59, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor60, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor61, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor62, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor63, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor64, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor65, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor66, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor67, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor68, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor69, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor70, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor71, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor72, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor73, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor74, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdColor75, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdIndividualColor, System.ComponentModel.ISupportInitialize).EndInit()
        CType(pbxSelection, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents grp As VisiWinNET.Forms.GroupBox
    Friend WithEvents vinBlue As VisiWinNET.Forms.VarIn
    Friend WithEvents vinGreen As VisiWinNET.Forms.VarIn
    Friend WithEvents vinRed As VisiWinNET.Forms.VarIn
    Friend WithEvents cmdColor1 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor2 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor3 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor4 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor5 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor6 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor7 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor8 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor9 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor10 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor11 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor12 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor13 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor14 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor15 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor16 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor17 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor18 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor19 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor20 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor21 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor22 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor23 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor24 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor25 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor26 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor27 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor28 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor29 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor30 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor31 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor32 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor33 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor34 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor35 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor36 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor37 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor38 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor39 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor40 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor41 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor42 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor43 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor44 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor45 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor46 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor47 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor48 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor49 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor50 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor51 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor52 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor53 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor54 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor55 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor56 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor57 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor58 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor59 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor60 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor61 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor62 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor63 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor64 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor65 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor66 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor67 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor68 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor69 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor70 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor71 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor72 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor73 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor74 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdColor75 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdIndividualColor As VisiWinNET.Forms.CommandButton
    Friend WithEvents pbxSelection As VisiWinNET.Forms.PictureBox
    Friend WithEvents Label1 As VisiWinNET.Forms.Label
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape

End Class