'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FConfigManual

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FConfigManual.sfc"), False)
        GroupBox = loader.Find("GroupBox")
        lblBeep = loader.Find("lblBeep")
        SwitchBeep = loader.Find("SwitchBeep")
        lblSmokehouse = loader.Find("lblSmokehouse")
        SwitchSmokehouse = loader.Find("SwitchSmokehouse")
        lblChimney = loader.Find("lblChimney")
        SwitchChimney = loader.Find("SwitchChimney")
        lblValveHumidification = loader.Find("lblValveHumidification")
        SwitchValveHumidification = loader.Find("SwitchValveHumidification")
        lblControlTemperature = loader.Find("lblControlTemperature")
        SwitchControlTemperature = loader.Find("SwitchControlTemperature")
        lblMotor09 = loader.Find("lblMotor09")
        lblMotor08 = loader.Find("lblMotor08")
        lblMotor07 = loader.Find("lblMotor07")
        lblMotor06 = loader.Find("lblMotor06")
        lblMotor05 = loader.Find("lblMotor05")
        lblMotor04 = loader.Find("lblMotor04")
        lblMotor03 = loader.Find("lblMotor03")
        lblMotor02 = loader.Find("lblMotor02")
        lblMotor01 = loader.Find("lblMotor01")
        lblMotor00 = loader.Find("lblMotor00")
        SwitchMotor09 = loader.Find("SwitchMotor09")
        SwitchMotor08 = loader.Find("SwitchMotor08")
        SwitchMotor07 = loader.Find("SwitchMotor07")
        SwitchMotor06 = loader.Find("SwitchMotor06")
        SwitchMotor05 = loader.Find("SwitchMotor05")
        SwitchMotor04 = loader.Find("SwitchMotor04")
        SwitchMotor03 = loader.Find("SwitchMotor03")
        SwitchMotor02 = loader.Find("SwitchMotor02")
        SwitchMotor01 = loader.Find("SwitchMotor01")
        SwitchMotor00 = loader.Find("SwitchMotor00")
        lblChambers = loader.Find("lblChambers")
        Shape1 = loader.Find("Shape1")
        Shape2 = loader.Find("Shape2")
        Shape3 = loader.Find("Shape3")
        cmdReturn = loader.Find("cmdReturn")
        Shape4 = loader.Find("Shape4")
        CType(GroupBox, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox.ResumeLayout(False)
        CType(lblBeep, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchBeep, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblSmokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchSmokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblChimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchChimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblValveHumidification, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchValveHumidification, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblControlTemperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchControlTemperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblMotor09, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblMotor08, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblMotor07, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblMotor06, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblMotor05, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblMotor04, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblMotor03, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblMotor02, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblMotor01, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblMotor00, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchMotor09, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchMotor08, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchMotor07, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchMotor06, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchMotor05, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchMotor04, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchMotor03, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchMotor02, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchMotor01, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchMotor00, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblChambers, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdReturn, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape4, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents GroupBox As VisiWinNET.Forms.GroupBox
    Friend WithEvents lblBeep As VisiWinNET.Forms.Label
    Friend WithEvents SwitchBeep As VisiWinNET.Forms.Switch
    Friend WithEvents lblSmokehouse As VisiWinNET.Forms.Label
    Friend WithEvents SwitchSmokehouse As VisiWinNET.Forms.Switch
    Friend WithEvents lblChimney As VisiWinNET.Forms.Label
    Friend WithEvents SwitchChimney As VisiWinNET.Forms.Switch
    Friend WithEvents lblValveHumidification As VisiWinNET.Forms.Label
    Friend WithEvents SwitchValveHumidification As VisiWinNET.Forms.Switch
    Friend WithEvents lblControlTemperature As VisiWinNET.Forms.Label
    Friend WithEvents SwitchControlTemperature As VisiWinNET.Forms.Switch
    Friend WithEvents lblMotor09 As VisiWinNET.Forms.Label
    Friend WithEvents lblMotor08 As VisiWinNET.Forms.Label
    Friend WithEvents lblMotor07 As VisiWinNET.Forms.Label
    Friend WithEvents lblMotor06 As VisiWinNET.Forms.Label
    Friend WithEvents lblMotor05 As VisiWinNET.Forms.Label
    Friend WithEvents lblMotor04 As VisiWinNET.Forms.Label
    Friend WithEvents lblMotor03 As VisiWinNET.Forms.Label
    Friend WithEvents lblMotor02 As VisiWinNET.Forms.Label
    Friend WithEvents lblMotor01 As VisiWinNET.Forms.Label
    Friend WithEvents lblMotor00 As VisiWinNET.Forms.Label
    Friend WithEvents SwitchMotor09 As VisiWinNET.Forms.Switch
    Friend WithEvents SwitchMotor08 As VisiWinNET.Forms.Switch
    Friend WithEvents SwitchMotor07 As VisiWinNET.Forms.Switch
    Friend WithEvents SwitchMotor06 As VisiWinNET.Forms.Switch
    Friend WithEvents SwitchMotor05 As VisiWinNET.Forms.Switch
    Friend WithEvents SwitchMotor04 As VisiWinNET.Forms.Switch
    Friend WithEvents SwitchMotor03 As VisiWinNET.Forms.Switch
    Friend WithEvents SwitchMotor02 As VisiWinNET.Forms.Switch
    Friend WithEvents SwitchMotor01 As VisiWinNET.Forms.Switch
    Friend WithEvents SwitchMotor00 As VisiWinNET.Forms.Switch
    Friend WithEvents lblChambers As VisiWinNET.Forms.Label
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape3 As VisiWinNET.Forms.Shape
    Friend WithEvents cmdReturn As VisiWinNET.Forms.CommandButton
    Friend WithEvents Shape4 As VisiWinNET.Forms.Shape

End Class