'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FConfigTimers

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FConfigTimers.sfc"), False)
        GroupBox = loader.Find("GroupBox")
        VarInResponse = loader.Find("VarInResponse")
        VarInActivation = loader.Find("VarInActivation")
        VarIn2 = loader.Find("VarIn2")
        Shape1 = loader.Find("Shape1")
        Shape2 = loader.Find("Shape2")
        Shape3 = loader.Find("Shape3")
        cmdReturn = loader.Find("cmdReturn")
        Shape4 = loader.Find("Shape4")
        CType(GroupBox, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox.ResumeLayout(False)
        CType(VarInResponse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInActivation, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarIn2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdReturn, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape4, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents GroupBox As VisiWinNET.Forms.GroupBox
    Friend WithEvents VarInResponse As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInActivation As VisiWinNET.Forms.VarIn
    Friend WithEvents VarIn2 As VisiWinNET.Forms.VarIn
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape3 As VisiWinNET.Forms.Shape
    Friend WithEvents cmdReturn As VisiWinNET.Forms.CommandButton
    Friend WithEvents Shape4 As VisiWinNET.Forms.Shape

End Class