'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FConfigurations

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FConfigurations.sfc"), False)
        GroupBox = loader.Find("GroupBox")
        cmdConfigTimers = loader.Find("cmdConfigTimers")
        VarOut2 = loader.Find("VarOut2")
        Label2 = loader.Find("Label2")
        cboLanguage = loader.Find("cboLanguage")
        VarOut1 = loader.Find("VarOut1")
        DateTimeIn1 = loader.Find("DateTimeIn1")
        Label1 = loader.Find("Label1")
        cmdConfigManual = loader.Find("cmdConfigManual")
        cmdConfigSystem = loader.Find("cmdConfigSystem")
        cmdConfigControl = loader.Find("cmdConfigControl")
        cmdConfigParameters = loader.Find("cmdConfigParameters")
        Shape1 = loader.Find("Shape1")
        Shape2 = loader.Find("Shape2")
        Shape3 = loader.Find("Shape3")
        cmdReturn = loader.Find("cmdReturn")
        Shape4 = loader.Find("Shape4")
        CType(GroupBox, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox.ResumeLayout(False)
        CType(cmdConfigTimers, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarOut2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cboLanguage, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarOut1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(DateTimeIn1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdConfigManual, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdConfigSystem, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdConfigControl, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdConfigParameters, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdReturn, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape4, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents GroupBox As VisiWinNET.Forms.GroupBox
    Friend WithEvents cmdConfigTimers As VisiWinNET.Forms.CommandButton
    Friend WithEvents VarOut2 As VisiWinNET.Forms.VarOut
    Friend WithEvents Label2 As VisiWinNET.Forms.Label
    Friend WithEvents cboLanguage As VisiWinNET.Forms.LanguageSwitching.LanguageComboBox
    Friend WithEvents VarOut1 As VisiWinNET.Forms.VarOut
    Friend WithEvents DateTimeIn1 As VisiWinNET.Forms.DateTimeIn
    Friend WithEvents Label1 As VisiWinNET.Forms.Label
    Friend WithEvents cmdConfigManual As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdConfigSystem As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdConfigControl As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdConfigParameters As VisiWinNET.Forms.CommandButton
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape3 As VisiWinNET.Forms.Shape
    Friend WithEvents cmdReturn As VisiWinNET.Forms.CommandButton
    Friend WithEvents Shape4 As VisiWinNET.Forms.Shape

End Class