'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FConfigSystem

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FConfigSystem.sfc"), False)
        GroupBox = loader.Find("GroupBox")
        lblChambers = loader.Find("lblChambers")
        VarInHumidityOffset = loader.Find("VarInHumidityOffset")
        VarInChamberTemperatureOffset = loader.Find("VarInChamberTemperatureOffset")
        VarInCoreTemperatureOffset = loader.Find("VarInCoreTemperatureOffset")
        Shape1 = loader.Find("Shape1")
        Shape2 = loader.Find("Shape2")
        Shape3 = loader.Find("Shape3")
        cmdReturn = loader.Find("cmdReturn")
        Shape4 = loader.Find("Shape4")
        CType(GroupBox, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox.ResumeLayout(False)
        CType(lblChambers, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInHumidityOffset, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInChamberTemperatureOffset, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCoreTemperatureOffset, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdReturn, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape4, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents GroupBox As VisiWinNET.Forms.GroupBox
    Friend WithEvents lblChambers As VisiWinNET.Forms.Label
    Friend WithEvents VarInHumidityOffset As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInChamberTemperatureOffset As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInCoreTemperatureOffset As VisiWinNET.Forms.VarIn
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape3 As VisiWinNET.Forms.Shape
    Friend WithEvents cmdReturn As VisiWinNET.Forms.CommandButton
    Friend WithEvents Shape4 As VisiWinNET.Forms.Shape

End Class