'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FGraphic

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FGraphic.sfc"), False)
        ItemServerTrendTime = loader.Find("ItemServerTrendTime")
        GroupBox = loader.Find("GroupBox")
        ExtendedSliderResolution = loader.Find("ExtendedSliderResolution")
        cmdOptions = loader.Find("cmdOptions")
        cmd1Day = loader.Find("cmd1Day")
        cmd1Hour = loader.Find("cmd1Hour")
        cmd5Minutes = loader.Find("cmd5Minutes")
        cmd1Minute = loader.Find("cmd1Minute")
        ExtendedSliderMax = loader.Find("ExtendedSliderMax")
        ExtendedSliderMin = loader.Find("ExtendedSliderMin")
        TrendChart = loader.Find("TrendChart")
        TrendLegend = loader.Find("TrendLegend")
        TrendTime = loader.Find("TrendTime")
        Shape4 = loader.Find("Shape4")
        Shape3 = loader.Find("Shape3")
        Shape2 = loader.Find("Shape2")
        cmdReturn = loader.Find("cmdReturn")
        Shape1 = loader.Find("Shape1")
        CType(ItemServerTrendTime, System.ComponentModel.ISupportInitialize).EndInit()
        CType(GroupBox, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox.ResumeLayout(False)
        CType(ExtendedSliderResolution, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdOptions, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd1Day, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd1Hour, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd5Minutes, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd1Minute, System.ComponentModel.ISupportInitialize).EndInit()
        CType(ExtendedSliderMax, System.ComponentModel.ISupportInitialize).EndInit()
        CType(ExtendedSliderMin, System.ComponentModel.ISupportInitialize).EndInit()
        CType(TrendChart, System.ComponentModel.ISupportInitialize).EndInit()
        CType(TrendLegend, System.ComponentModel.ISupportInitialize).EndInit()
        CType(TrendTime, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdReturn, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents ItemServerTrendTime As VisiWinNET.Forms.ItemServer
    Friend WithEvents GroupBox As VisiWinNET.Forms.GroupBox
    Friend WithEvents ExtendedSliderResolution As VisiWinNET.Forms.ExtendedSlider
    Friend WithEvents cmdOptions As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd1Day As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd1Hour As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd5Minutes As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd1Minute As VisiWinNET.Forms.CommandButton
    Friend WithEvents ExtendedSliderMax As VisiWinNET.Forms.ExtendedSlider
    Friend WithEvents ExtendedSliderMin As VisiWinNET.Forms.ExtendedSlider
    Friend WithEvents TrendChart As VisiWinNET.Forms.Trend.TrendChart
    Friend WithEvents TrendLegend As VisiWinNET.Forms.Trend.TrendLegend
    Friend WithEvents TrendTime As VisiWinNET.Forms.Trend.TrendTime
    Friend WithEvents Shape4 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape3 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents cmdReturn As VisiWinNET.Forms.CommandButton
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape

End Class