'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FHistoric

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FHistoric.sfc"), False)
        UpdateListTrigger = loader.Find("UpdateListTrigger")
        GroupBox = loader.Find("GroupBox")
        LogBookList = loader.Find("LogBookList")
        cmdReturn = loader.Find("cmdReturn")
        Shape2 = loader.Find("Shape2")
        Shape3 = loader.Find("Shape3")
        Shape4 = loader.Find("Shape4")
        Shape5 = loader.Find("Shape5")
        cmdUpdate = loader.Find("cmdUpdate")
        CType(UpdateListTrigger, System.ComponentModel.ISupportInitialize).EndInit()
        CType(GroupBox, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox.ResumeLayout(False)
        CType(LogBookList, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdReturn, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape5, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdUpdate, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents UpdateListTrigger As VisiWinNET.Forms.ItemServer
    Friend WithEvents GroupBox As VisiWinNET.Forms.GroupBox
    Friend WithEvents LogBookList As VisiWinNET.Forms.Alarm.HistoricalAlarmList
    Friend WithEvents cmdReturn As VisiWinNET.Forms.CommandButton
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape3 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape4 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape5 As VisiWinNET.Forms.Shape
    Friend WithEvents cmdUpdate As VisiWinNET.Forms.CommandButton

End Class