'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FMessageBox

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FMessageBox.sfc"), False)
        lblMessage = loader.Find("lblMessage")
        Shape2 = loader.Find("Shape2")
        lblCaption = loader.Find("lblCaption")
        cmdButton002 = loader.Find("cmdButton002")
        cmdButton001 = loader.Find("cmdButton001")
        cmdButton000 = loader.Find("cmdButton000")
        Shape1 = loader.Find("Shape1")
        TimerClose = loader.Find("TimerClose")
        CType(lblMessage, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblCaption, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdButton002, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdButton001, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdButton000, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(TimerClose, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents lblMessage As VisiWinNET.Forms.Label
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents lblCaption As VisiWinNET.Forms.Label
    Friend WithEvents cmdButton002 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdButton001 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdButton000 As VisiWinNET.Forms.CommandButton
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents TimerClose As VisiWinNET.Forms.Timer

End Class