'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FNumPad

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FNumPad.sfc"), False)
        grpBorder = loader.Find("grpBorder")
        cmdEsc = loader.Find("cmdEsc")
        pnlPicLimitMin = loader.Find("pnlPicLimitMin")
        pnlPicLimitMax = loader.Find("pnlPicLimitMax")
        lblUnit = loader.Find("lblUnit")
        numEdit = loader.Find("numEdit")
        lbInputBack = loader.Find("lbInputBack")
        vouMinValue = loader.Find("vouMinValue")
        vouMaxValue = loader.Find("vouMaxValue")
        lblCaption = loader.Find("lblCaption")
        cmdLeft = loader.Find("cmdLeft")
        cmdRight = loader.Find("cmdRight")
        cmdClear = loader.Find("cmdClear")
        cmdBack = loader.Find("cmdBack")
        cmdEnter = loader.Find("cmdEnter")
        cmdDel = loader.Find("cmdDel")
        cmdEnd = loader.Find("cmdEnd")
        cmdHome = loader.Find("cmdHome")
        cmd0 = loader.Find("cmd0")
        cmdDecSep = loader.Find("cmdDecSep")
        cmd1 = loader.Find("cmd1")
        cmd2 = loader.Find("cmd2")
        cmd4 = loader.Find("cmd4")
        cmd7 = loader.Find("cmd7")
        cmd5 = loader.Find("cmd5")
        cmd8 = loader.Find("cmd8")
        cmd9 = loader.Find("cmd9")
        cmd6 = loader.Find("cmd6")
        cmd3 = loader.Find("cmd3")
        cmdSign = loader.Find("cmdSign")
        cmdExponent = loader.Find("cmdExponent")
        CType(grpBorder, System.ComponentModel.ISupportInitialize).EndInit()
        grpBorder.ResumeLayout(False)
        CType(cmdEsc, System.ComponentModel.ISupportInitialize).EndInit()
        CType(pnlPicLimitMin, System.ComponentModel.ISupportInitialize).EndInit()
        CType(pnlPicLimitMax, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblUnit, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lbInputBack, System.ComponentModel.ISupportInitialize).EndInit()
        CType(vouMinValue, System.ComponentModel.ISupportInitialize).EndInit()
        CType(vouMaxValue, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblCaption, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdLeft, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdRight, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdClear, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdBack, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdEnter, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdDel, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdEnd, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdHome, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd0, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdDecSep, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd7, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd5, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd8, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd9, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd6, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmd3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdSign, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdExponent, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents grpBorder As VisiWinNET.Forms.GroupBox
    Friend WithEvents cmdEsc As VisiWinNET.Forms.CommandButton
    Friend WithEvents pnlPicLimitMin As VisiWinNET.Forms.PictureBox
    Friend WithEvents pnlPicLimitMax As VisiWinNET.Forms.PictureBox
    Friend WithEvents lblUnit As VisiWinNET.Forms.Label
    Friend WithEvents numEdit As VisiWinNET.Forms.Internals.NumEdit
    Friend WithEvents lbInputBack As VisiWinNET.Forms.Label
    Friend WithEvents vouMinValue As VisiWinNET.Forms.VarOut
    Friend WithEvents vouMaxValue As VisiWinNET.Forms.VarOut
    Friend WithEvents lblCaption As VisiWinNET.Forms.Label
    Friend WithEvents cmdLeft As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdRight As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdClear As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdBack As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdEnter As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdDel As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdEnd As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdHome As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd0 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdDecSep As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd1 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd2 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd4 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd7 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd5 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd8 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd9 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd6 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmd3 As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdSign As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdExponent As VisiWinNET.Forms.CommandButton

End Class