'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class Form

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "Form.sfc"), False)
        GroupBoxButtonLine = loader.Find("GroupBoxButtonLine")
        CommandButtonBack = loader.Find("CommandButtonBack")
        CommandButton2 = loader.Find("CommandButton2")
        CommandButton1 = loader.Find("CommandButton1")
        GroupBoxHeader = loader.Find("GroupBoxHeader")
        GroupBoxHeaderLine = loader.Find("GroupBoxHeaderLine")
        LabelFormName = loader.Find("LabelFormName")
        DateTimeOut = loader.Find("DateTimeOut")
        PictureBoxLogo = loader.Find("PictureBoxLogo")
        AlarmLine = loader.Find("AlarmLine")
        GroupBox1 = loader.Find("GroupBox1")
        Label2 = loader.Find("Label2")
        Label3 = loader.Find("Label3")
        CType(GroupBoxButtonLine, System.ComponentModel.ISupportInitialize).EndInit()
		GroupBoxButtonLine.ResumeLayout(False)
        CType(CommandButtonBack, System.ComponentModel.ISupportInitialize).EndInit()
        CType(CommandButton2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(CommandButton1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(GroupBoxHeader, System.ComponentModel.ISupportInitialize).EndInit()
		GroupBoxHeader.ResumeLayout(False)
        CType(GroupBoxHeaderLine, System.ComponentModel.ISupportInitialize).EndInit()
		GroupBoxHeaderLine.ResumeLayout(False)
        CType(LabelFormName, System.ComponentModel.ISupportInitialize).EndInit()
        CType(DateTimeOut, System.ComponentModel.ISupportInitialize).EndInit()
        CType(PictureBoxLogo, System.ComponentModel.ISupportInitialize).EndInit()
        CType(AlarmLine, System.ComponentModel.ISupportInitialize).EndInit()
        CType(GroupBox1, System.ComponentModel.ISupportInitialize).EndInit()
		GroupBox1.ResumeLayout(False)
        CType(Label2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label3, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents GroupBoxButtonLine As VisiWinNET.Forms.GroupBox
    Friend WithEvents CommandButtonBack As VisiWinNET.Forms.CommandButton
    Friend WithEvents CommandButton2 As VisiWinNET.Forms.CommandButton
    Friend WithEvents CommandButton1 As VisiWinNET.Forms.CommandButton
    Friend WithEvents GroupBoxHeader As VisiWinNET.Forms.GroupBox
    Friend WithEvents GroupBoxHeaderLine As VisiWinNET.Forms.GroupBox
    Friend WithEvents LabelFormName As VisiWinNET.Forms.Label
    Friend WithEvents DateTimeOut As VisiWinNET.Forms.DateTimeOut
    Friend WithEvents PictureBoxLogo As VisiWinNET.Forms.PictureBox
    Friend WithEvents AlarmLine As VisiWinNET.Forms.Alarm.AlarmLine
    Friend WithEvents GroupBox1 As VisiWinNET.Forms.GroupBox
    Friend WithEvents Label2 As VisiWinNET.Forms.Label
    Friend WithEvents Label3 As VisiWinNET.Forms.Label

End Class