'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FProcess

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FProcess.sfc"), False)
        RearmTimer = loader.Find("RearmTimer")
        GroupBox = loader.Find("GroupBox")
        Label001 = loader.Find("Label001")
        VarOutEstimatedTime = loader.Find("VarOutEstimatedTime")
        VarOutNumberSteps = loader.Find("VarOutNumberSteps")
        Label004 = loader.Find("Label004")
        DateTimeOutEstimated = loader.Find("DateTimeOutEstimated")
        cmdStart = loader.Find("cmdStart")
        Label002 = loader.Find("Label002")
        VarOutSteps = loader.Find("VarOutSteps")
        Label003 = loader.Find("Label003")
        cmdReturn = loader.Find("cmdReturn")
        DateTimeOutInitProcess = loader.Find("DateTimeOutInitProcess")
        lblChambers = loader.Find("lblChambers")
        VarOutNumberCycles = loader.Find("VarOutNumberCycles")
        cmdPause = loader.Find("cmdPause")
        VarOutElapsedTime = loader.Find("VarOutElapsedTime")
        cmdStop = loader.Find("cmdStop")
        VarOutCycles = loader.Find("VarOutCycles")
        lblStatus = loader.Find("lblStatus")
        VarOutRecipeDescription = loader.Find("VarOutRecipeDescription")
        VarOutProgrammedRecipe = loader.Find("VarOutProgrammedRecipe")
        Label000 = loader.Find("Label000")
        Shape1 = loader.Find("Shape1")
        Shape2 = loader.Find("Shape2")
        Shape3 = loader.Find("Shape3")
        Shape4 = loader.Find("Shape4")
        CType(RearmTimer, System.ComponentModel.ISupportInitialize).EndInit()
        CType(GroupBox, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox.ResumeLayout(False)
        CType(Label001, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarOutEstimatedTime, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarOutNumberSteps, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label004, System.ComponentModel.ISupportInitialize).EndInit()
        CType(DateTimeOutEstimated, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdStart, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label002, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarOutSteps, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label003, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdReturn, System.ComponentModel.ISupportInitialize).EndInit()
        CType(DateTimeOutInitProcess, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblChambers, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarOutNumberCycles, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdPause, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarOutElapsedTime, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdStop, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarOutCycles, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblStatus, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarOutRecipeDescription, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarOutProgrammedRecipe, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label000, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape4, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents RearmTimer As VisiWinNET.Forms.Timer
    Friend WithEvents GroupBox As VisiWinNET.Forms.GroupBox
    Friend WithEvents Label001 As VisiWinNET.Forms.Label
    Friend WithEvents VarOutEstimatedTime As VisiWinNET.Forms.VarOut
    Friend WithEvents VarOutNumberSteps As VisiWinNET.Forms.VarOut
    Friend WithEvents Label004 As VisiWinNET.Forms.Label
    Friend WithEvents DateTimeOutEstimated As VisiWinNET.Forms.DateTimeOut
    Friend WithEvents cmdStart As VisiWinNET.Forms.CommandButton
    Friend WithEvents Label002 As VisiWinNET.Forms.Label
    Friend WithEvents VarOutSteps As VisiWinNET.Forms.VarOut
    Friend WithEvents Label003 As VisiWinNET.Forms.Label
    Friend WithEvents cmdReturn As VisiWinNET.Forms.CommandButton
    Friend WithEvents DateTimeOutInitProcess As VisiWinNET.Forms.DateTimeOut
    Friend WithEvents lblChambers As VisiWinNET.Forms.Label
    Friend WithEvents VarOutNumberCycles As VisiWinNET.Forms.VarOut
    Friend WithEvents cmdPause As VisiWinNET.Forms.CommandButton
    Friend WithEvents VarOutElapsedTime As VisiWinNET.Forms.VarOut
    Friend WithEvents cmdStop As VisiWinNET.Forms.CommandButton
    Friend WithEvents VarOutCycles As VisiWinNET.Forms.VarOut
    Friend WithEvents lblStatus As VisiWinNET.Forms.Label
    Friend WithEvents VarOutRecipeDescription As VisiWinNET.Forms.VarOut
    Friend WithEvents VarOutProgrammedRecipe As VisiWinNET.Forms.VarOut
    Friend WithEvents Label000 As VisiWinNET.Forms.Label
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape3 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape4 As VisiWinNET.Forms.Shape

End Class