'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FRecipeFile

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FRecipeFile.sfc"), False)
        cmdSaveOK = loader.Find("cmdSaveOK")
        cmdLoadOK = loader.Find("cmdLoadOK")
        cmdDelete = loader.Find("cmdDelete")
        vinFileDescription = loader.Find("vinFileDescription")
        vinFileName = loader.Find("vinFileName")
        lvFiles = loader.Find("lvFiles")
        cmdCancel = loader.Find("cmdCancel")
        RecipeClassHandler = loader.Find("RecipeClassHandler")
        Shape1 = loader.Find("Shape1")
        Label1 = loader.Find("Label1")
        Shape2 = loader.Find("Shape2")
        CType(cmdSaveOK, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdLoadOK, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdDelete, System.ComponentModel.ISupportInitialize).EndInit()
        CType(vinFileDescription, System.ComponentModel.ISupportInitialize).EndInit()
        CType(vinFileName, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lvFiles, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdCancel, System.ComponentModel.ISupportInitialize).EndInit()
        CType(RecipeClassHandler, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents cmdSaveOK As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdLoadOK As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdDelete As VisiWinNET.Forms.CommandButton
    Friend WithEvents vinFileDescription As VisiWinNET.Forms.VarIn
    Friend WithEvents vinFileName As VisiWinNET.Forms.VarIn
    Friend WithEvents lvFiles As VisiWinNET.Forms.Recipe.RecipeList
    Friend WithEvents cmdCancel As VisiWinNET.Forms.CommandButton
    Friend WithEvents RecipeClassHandler As VisiWinNET.Forms.Recipe.RecipeClassHandler
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Label1 As VisiWinNET.Forms.Label
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape

End Class