'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FRecipes

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FRecipes.sfc"), False)
        RecipeClassHandler = loader.Find("RecipeClassHandler")
        GroupBox = loader.Find("GroupBox")
        cmdChange = loader.Find("cmdChange")
        VarDescription = loader.Find("VarDescription")
        LblSmokehouse = loader.Find("LblSmokehouse")
        LblChimney = loader.Find("LblChimney")
        LblHumidity = loader.Find("LblHumidity")
        LblTime = loader.Find("LblTime")
        cmdReturn = loader.Find("cmdReturn")
        LblTemperature = loader.Find("LblTemperature")
        cmdLoadRecipe = loader.Find("cmdLoadRecipe")
        VarInSteps = loader.Find("VarInSteps")
        cmdSaveRecipeAs = loader.Find("cmdSaveRecipeAs")
        VarInCycles = loader.Find("VarInCycles")
        cmdSetRecipe = loader.Find("cmdSetRecipe")
        VarInCycleCoreTemperature = loader.Find("VarInCycleCoreTemperature")
        VarInCycle00Temperature = loader.Find("VarInCycle00Temperature")
        varRecipename = loader.Find("varRecipename")
        VarInCycle01Temperature = loader.Find("VarInCycle01Temperature")
        SwitchCycle09Smokehouse = loader.Find("SwitchCycle09Smokehouse")
        VarInCycle02Temperature = loader.Find("VarInCycle02Temperature")
        SwitchCycle08Smokehouse = loader.Find("SwitchCycle08Smokehouse")
        VarInCycle03Temperature = loader.Find("VarInCycle03Temperature")
        SwitchCycle07Smokehouse = loader.Find("SwitchCycle07Smokehouse")
        VarInCycle04Temperature = loader.Find("VarInCycle04Temperature")
        SwitchCycle06Smokehouse = loader.Find("SwitchCycle06Smokehouse")
        VarInCycle05Temperature = loader.Find("VarInCycle05Temperature")
        SwitchCycle05Smokehouse = loader.Find("SwitchCycle05Smokehouse")
        VarInCycle06Temperature = loader.Find("VarInCycle06Temperature")
        SwitchCycle04Smokehouse = loader.Find("SwitchCycle04Smokehouse")
        VarInCycle07Temperature = loader.Find("VarInCycle07Temperature")
        SwitchCycle03Smokehouse = loader.Find("SwitchCycle03Smokehouse")
        VarInCycle08Temperature = loader.Find("VarInCycle08Temperature")
        SwitchCycle02Smokehouse = loader.Find("SwitchCycle02Smokehouse")
        VarInCycle09Temperature = loader.Find("VarInCycle09Temperature")
        SwitchCycle01Smokehouse = loader.Find("SwitchCycle01Smokehouse")
        VarInCycle00Timer = loader.Find("VarInCycle00Timer")
        SwitchCycle00Smokehouse = loader.Find("SwitchCycle00Smokehouse")
        VarInCycle01Timer = loader.Find("VarInCycle01Timer")
        SwitchCycle09Chimney = loader.Find("SwitchCycle09Chimney")
        VarInCycle02Timer = loader.Find("VarInCycle02Timer")
        SwitchCycle08Chimney = loader.Find("SwitchCycle08Chimney")
        VarInCycle03Timer = loader.Find("VarInCycle03Timer")
        SwitchCycle07Chimney = loader.Find("SwitchCycle07Chimney")
        VarInCycle04Timer = loader.Find("VarInCycle04Timer")
        SwitchCycle06Chimney = loader.Find("SwitchCycle06Chimney")
        VarInCycle05Timer = loader.Find("VarInCycle05Timer")
        SwitchCycle05Chimney = loader.Find("SwitchCycle05Chimney")
        VarInCycle06Timer = loader.Find("VarInCycle06Timer")
        SwitchCycle04Chimney = loader.Find("SwitchCycle04Chimney")
        VarInCycle07Timer = loader.Find("VarInCycle07Timer")
        SwitchCycle03Chimney = loader.Find("SwitchCycle03Chimney")
        VarInCycle08Timer = loader.Find("VarInCycle08Timer")
        SwitchCycle02Chimney = loader.Find("SwitchCycle02Chimney")
        VarInCycle09Timer = loader.Find("VarInCycle09Timer")
        SwitchCycle01Chimney = loader.Find("SwitchCycle01Chimney")
        VarInCycle00Humidity = loader.Find("VarInCycle00Humidity")
        SwitchCycle00Chimney = loader.Find("SwitchCycle00Chimney")
        VarInCycle01Humidity = loader.Find("VarInCycle01Humidity")
        VarInCycle09Humidity = loader.Find("VarInCycle09Humidity")
        VarInCycle02Humidity = loader.Find("VarInCycle02Humidity")
        VarInCycle08Humidity = loader.Find("VarInCycle08Humidity")
        VarInCycle03Humidity = loader.Find("VarInCycle03Humidity")
        VarInCycle07Humidity = loader.Find("VarInCycle07Humidity")
        VarInCycle04Humidity = loader.Find("VarInCycle04Humidity")
        VarInCycle06Humidity = loader.Find("VarInCycle06Humidity")
        VarInCycle05Humidity = loader.Find("VarInCycle05Humidity")
        Shape1 = loader.Find("Shape1")
        Shape2 = loader.Find("Shape2")
        Shape3 = loader.Find("Shape3")
        Shape4 = loader.Find("Shape4")
        CType(RecipeClassHandler, System.ComponentModel.ISupportInitialize).EndInit()
        CType(GroupBox, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox.ResumeLayout(False)
        CType(cmdChange, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarDescription, System.ComponentModel.ISupportInitialize).EndInit()
        CType(LblSmokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(LblChimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(LblHumidity, System.ComponentModel.ISupportInitialize).EndInit()
        CType(LblTime, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdReturn, System.ComponentModel.ISupportInitialize).EndInit()
        CType(LblTemperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdLoadRecipe, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInSteps, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdSaveRecipeAs, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycles, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdSetRecipe, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycleCoreTemperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle00Temperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(varRecipename, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle01Temperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle09Smokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle02Temperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle08Smokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle03Temperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle07Smokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle04Temperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle06Smokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle05Temperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle05Smokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle06Temperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle04Smokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle07Temperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle03Smokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle08Temperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle02Smokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle09Temperature, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle01Smokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle00Timer, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle00Smokehouse, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle01Timer, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle09Chimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle02Timer, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle08Chimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle03Timer, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle07Chimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle04Timer, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle06Chimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle05Timer, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle05Chimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle06Timer, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle04Chimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle07Timer, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle03Chimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle08Timer, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle02Chimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle09Timer, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle01Chimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle00Humidity, System.ComponentModel.ISupportInitialize).EndInit()
        CType(SwitchCycle00Chimney, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle01Humidity, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle09Humidity, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle02Humidity, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle08Humidity, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle03Humidity, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle07Humidity, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle04Humidity, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle06Humidity, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VarInCycle05Humidity, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape4, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents RecipeClassHandler As VisiWinNET.Forms.Recipe.RecipeClassHandler
    Friend WithEvents GroupBox As VisiWinNET.Forms.GroupBox
    Friend WithEvents cmdChange As VisiWinNET.Forms.CommandButton
    Friend WithEvents VarDescription As VisiWinNET.Forms.VarOut
    Friend WithEvents LblSmokehouse As VisiWinNET.Forms.Label
    Friend WithEvents LblChimney As VisiWinNET.Forms.Label
    Friend WithEvents LblHumidity As VisiWinNET.Forms.Label
    Friend WithEvents LblTime As VisiWinNET.Forms.Label
    Friend WithEvents cmdReturn As VisiWinNET.Forms.CommandButton
    Friend WithEvents LblTemperature As VisiWinNET.Forms.Label
    Friend WithEvents cmdLoadRecipe As VisiWinNET.Forms.CommandButton
    Friend WithEvents VarInSteps As VisiWinNET.Forms.VarIn
    Friend WithEvents cmdSaveRecipeAs As VisiWinNET.Forms.CommandButton
    Friend WithEvents VarInCycles As VisiWinNET.Forms.VarIn
    Friend WithEvents cmdSetRecipe As VisiWinNET.Forms.CommandButton
    Friend WithEvents VarInCycleCoreTemperature As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInCycle00Temperature As VisiWinNET.Forms.VarIn
    Friend WithEvents varRecipename As VisiWinNET.Forms.VarOut
    Friend WithEvents VarInCycle01Temperature As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle09Smokehouse As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle02Temperature As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle08Smokehouse As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle03Temperature As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle07Smokehouse As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle04Temperature As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle06Smokehouse As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle05Temperature As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle05Smokehouse As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle06Temperature As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle04Smokehouse As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle07Temperature As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle03Smokehouse As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle08Temperature As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle02Smokehouse As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle09Temperature As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle01Smokehouse As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle00Timer As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle00Smokehouse As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle01Timer As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle09Chimney As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle02Timer As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle08Chimney As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle03Timer As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle07Chimney As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle04Timer As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle06Chimney As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle05Timer As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle05Chimney As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle06Timer As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle04Chimney As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle07Timer As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle03Chimney As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle08Timer As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle02Chimney As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle09Timer As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle01Chimney As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle00Humidity As VisiWinNET.Forms.VarIn
    Friend WithEvents SwitchCycle00Chimney As VisiWinNET.Forms.Switch
    Friend WithEvents VarInCycle01Humidity As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInCycle09Humidity As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInCycle02Humidity As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInCycle08Humidity As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInCycle03Humidity As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInCycle07Humidity As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInCycle04Humidity As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInCycle06Humidity As VisiWinNET.Forms.VarIn
    Friend WithEvents VarInCycle05Humidity As VisiWinNET.Forms.VarIn
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape3 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape4 As VisiWinNET.Forms.Shape

End Class