'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FSelectBox

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FSelectBox.sfc"), False)
        TimerClose = loader.Find("TimerClose")
        lblLabel = loader.Find("lblLabel")
        cboChamber = loader.Find("cboChamber")
        Shape2 = loader.Find("Shape2")
        lblCaption = loader.Find("lblCaption")
        cmdCancel = loader.Find("cmdCancel")
        cmdOk = loader.Find("cmdOk")
        Shape1 = loader.Find("Shape1")
        CType(TimerClose, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblLabel, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cboChamber, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lblCaption, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdCancel, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdOk, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents TimerClose As VisiWinNET.Forms.Timer
    Friend WithEvents lblLabel As VisiWinNET.Forms.Label
    Friend WithEvents cboChamber As VisiWinNET.Forms.ComboBox
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents lblCaption As VisiWinNET.Forms.Label
    Friend WithEvents cmdCancel As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdOk As VisiWinNET.Forms.CommandButton
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape

End Class