'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FSystemOptions

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FSystemOptions.sfc"), False)
        Label000 = loader.Find("Label000")
        cmdConfigurations = loader.Find("cmdConfigurations")
        cmdHistoric = loader.Find("cmdHistoric")
        cmdUsers = loader.Find("cmdUsers")
        cmdGrafics = loader.Find("cmdGrafics")
        cmdSynoptic = loader.Find("cmdSynoptic")
        cmdProcess = loader.Find("cmdProcess")
        cmdRecipes = loader.Find("cmdRecipes")
        cmdAlarms = loader.Find("cmdAlarms")
        cmdLogOff = loader.Find("cmdLogOff")
        Shape1 = loader.Find("Shape1")
        Shape2 = loader.Find("Shape2")
        CType(Label000, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdConfigurations, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdHistoric, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdUsers, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdGrafics, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdSynoptic, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdProcess, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdRecipes, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdAlarms, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdLogOff, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents Label000 As VisiWinNET.Forms.Label
    Friend WithEvents cmdConfigurations As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdHistoric As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdUsers As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdGrafics As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdSynoptic As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdProcess As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdRecipes As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdAlarms As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdLogOff As VisiWinNET.Forms.CommandButton
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape

End Class