'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FUsers

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FUsers.sfc"), False)
        TimerDeactivated = loader.Find("TimerDeactivated")
        TimerChange = loader.Find("TimerChange")
        lvwUsers = loader.Find("lvwUsers")
        cmdRemove = loader.Find("cmdRemove")
        cmdDeactivate = loader.Find("cmdDeactivate")
        CmdActivate = loader.Find("CmdActivate")
        cmdChange = loader.Find("cmdChange")
        cmdAdd = loader.Find("cmdAdd")
        cmdReturn = loader.Find("cmdReturn")
        GroupBox = loader.Find("GroupBox")
        Shape1 = loader.Find("Shape1")
        Shape2 = loader.Find("Shape2")
        Shape3 = loader.Find("Shape3")
        Shape4 = loader.Find("Shape4")
        CType(TimerDeactivated, System.ComponentModel.ISupportInitialize).EndInit()
        CType(TimerChange, System.ComponentModel.ISupportInitialize).EndInit()
        CType(lvwUsers, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdRemove, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdDeactivate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(CmdActivate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdChange, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdAdd, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdReturn, System.ComponentModel.ISupportInitialize).EndInit()
        CType(GroupBox, System.ComponentModel.ISupportInitialize).EndInit()
        GroupBox.ResumeLayout(False)
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape4, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents TimerDeactivated As VisiWinNET.Forms.Timer
    Friend WithEvents TimerChange As VisiWinNET.Forms.Timer
    Friend WithEvents lvwUsers As VisiWinNET.Forms.ListView
    Friend WithEvents cmdRemove As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdDeactivate As VisiWinNET.Forms.CommandButton
    Friend WithEvents CmdActivate As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdChange As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdAdd As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdReturn As VisiWinNET.Forms.CommandButton
    Friend WithEvents GroupBox As VisiWinNET.Forms.GroupBox
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape3 As VisiWinNET.Forms.Shape
    Friend WithEvents Shape4 As VisiWinNET.Forms.Shape

End Class