'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class FUserChange

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "FUserChange.sfc"), False)
        chkChangeMachineCode = loader.Find("chkChangeMachineCode")
        chkChangePassword = loader.Find("chkChangePassword")
        cboState = loader.Find("cboState")
        Label1 = loader.Find("Label1")
        vinComment = loader.Find("vinComment")
        Label3 = loader.Find("Label3")
        VinMachineCode = loader.Find("VinMachineCode")
        cboUserGroups = loader.Find("cboUserGroups")
        vinRepeatPassword = loader.Find("vinRepeatPassword")
        VinFullName = loader.Find("VinFullName")
        cmdCancel = loader.Find("cmdCancel")
        cmdOk = loader.Find("cmdOk")
        vinPassword = loader.Find("vinPassword")
        vinName = loader.Find("vinName")
        Shape1 = loader.Find("Shape1")
        Label2 = loader.Find("Label2")
        Shape2 = loader.Find("Shape2")
        CType(chkChangeMachineCode, System.ComponentModel.ISupportInitialize).EndInit()
        CType(chkChangePassword, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cboState, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(vinComment, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VinMachineCode, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cboUserGroups, System.ComponentModel.ISupportInitialize).EndInit()
        CType(vinRepeatPassword, System.ComponentModel.ISupportInitialize).EndInit()
        CType(VinFullName, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdCancel, System.ComponentModel.ISupportInitialize).EndInit()
        CType(cmdOk, System.ComponentModel.ISupportInitialize).EndInit()
        CType(vinPassword, System.ComponentModel.ISupportInitialize).EndInit()
        CType(vinName, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Shape2, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents chkChangeMachineCode As VisiWinNET.Forms.CheckBox
    Friend WithEvents chkChangePassword As VisiWinNET.Forms.CheckBox
    Friend WithEvents cboState As VisiWinNET.Forms.ComboBox
    Friend WithEvents Label1 As VisiWinNET.Forms.Label
    Friend WithEvents vinComment As VisiWinNET.Forms.VarIn
    Friend WithEvents Label3 As VisiWinNET.Forms.Label
    Friend WithEvents VinMachineCode As VisiWinNET.Forms.VarIn
    Friend WithEvents cboUserGroups As VisiWinNET.Forms.ComboBox
    Friend WithEvents vinRepeatPassword As VisiWinNET.Forms.VarIn
    Friend WithEvents VinFullName As VisiWinNET.Forms.VarIn
    Friend WithEvents cmdCancel As VisiWinNET.Forms.CommandButton
    Friend WithEvents cmdOk As VisiWinNET.Forms.CommandButton
    Friend WithEvents vinPassword As VisiWinNET.Forms.VarIn
    Friend WithEvents vinName As VisiWinNET.Forms.VarIn
    Friend WithEvents Shape1 As VisiWinNET.Forms.Shape
    Friend WithEvents Label2 As VisiWinNET.Forms.Label
    Friend WithEvents Shape2 As VisiWinNET.Forms.Shape

End Class