'---------------------------------------------------------
' This file was generated by VisiWinNET
' 
' Attention:
' Changes to this file may cause incorrect behavior 
' and will be lost if the file is regenerated.
'
'---------------------------------------------------------

Partial Class ReadMe

    Private Sub InitializeComponent()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
		Me.SuspendLayout()
        Dim loader As New VisiWinNET.Forms.Internals.SFCLoader(Me)
        loader.Load(System.IO.Path.Combine(VisiWinNET.Project.ProjectInfo.Path, "ReadMe.sfc"), False)
        GroupBoxInfo = loader.Find("GroupBoxInfo")
        Label8 = loader.Find("Label8")
        Label7 = loader.Find("Label7")
        Label6 = loader.Find("Label6")
        Label5 = loader.Find("Label5")
        Label4 = loader.Find("Label4")
        Label1 = loader.Find("Label1")
        Label2 = loader.Find("Label2")
        Label3 = loader.Find("Label3")
        Label9 = loader.Find("Label9")
        CType(GroupBoxInfo, System.ComponentModel.ISupportInitialize).EndInit()
		GroupBoxInfo.ResumeLayout(False)
        CType(Label8, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label7, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label6, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label5, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Label9, System.ComponentModel.ISupportInitialize).EndInit()

        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
		Me.ResumeLayout(False)
    End Sub
    
    Friend WithEvents GroupBoxInfo As VisiWinNET.Forms.GroupBox
    Friend WithEvents Label8 As VisiWinNET.Forms.Label
    Friend WithEvents Label7 As VisiWinNET.Forms.Label
    Friend WithEvents Label6 As VisiWinNET.Forms.Label
    Friend WithEvents Label5 As VisiWinNET.Forms.Label
    Friend WithEvents Label4 As VisiWinNET.Forms.Label
    Friend WithEvents Label1 As VisiWinNET.Forms.Label
    Friend WithEvents Label2 As VisiWinNET.Forms.Label
    Friend WithEvents Label3 As VisiWinNET.Forms.Label
    Friend WithEvents Label9 As VisiWinNET.Forms.Label

End Class